[package]
name = "aequora-journal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
aequora-protocol = { version = "0.1.0", path = "../aequora-protocol" }
aequora-types = { version = "0.1.0", path = "../aequora-types" }
thiserror.workspace = true

[lints]
workspace = true

