[package]
name = "aequora-axum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
aequora-codec = { version = "0.1.0", path = "../aequora-codec", features = ["zstd"] }
aequora-executor = { version = "0.1.0", path = "../aequora-executor" }
aequora-observability = { version = "0.1.0", path = "../aequora-observability" }
aequora-protocol = { version = "0.1.0", path = "../aequora-protocol" }
aequora-server = { version = "0.1.0", path = "../aequora-server" }
aequora-store = { version = "0.1.0", path = "../aequora-store" }
axum.workspace = true
bytes.workspace = true
http.workspace = true

[lints]
workspace = true

[dev-dependencies]
aequora-types = { version = "0.1.0", path = "../aequora-types" }
async-trait.workspace = true
tokio.workspace = true
tower.workspace = true
