[package]
name = "aequora-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
aequora-authority = { version = "0.1.1", path = "../aequora-authority" }
aequora-coordination = { version = "0.1.1", path = "../aequora-coordination" }
aequora-executor = { version = "0.1.1", path = "../aequora-executor" }
aequora-integrity = { version = "0.1.1", path = "../aequora-integrity" }
aequora-protocol = { version = "0.1.1", path = "../aequora-protocol" }
aequora-queue = { version = "0.1.1", path = "../aequora-queue" }
aequora-scope = { version = "0.1.1", path = "../aequora-scope" }
aequora-types = { version = "0.1.1", path = "../aequora-types" }
async-trait.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
