[package]
name = "aequora-registry-generated"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Build-generated immutable Aequora durable registry"
build = "build.rs"

[dependencies]
aequora-registry-types = { version = "0.1.1", path = "../aequora-registry-types" }

[build-dependencies]
aequora-registry-codegen = { version = "0.1.1", path = "../aequora-registry-codegen" }

[lints]
workspace = true
