[package]
name = "aequora-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
aequora-protocol = { version = "0.1.0", path = "../aequora-protocol" }
async-trait.workspace = true
thiserror.workspace = true

[lints]
workspace = true

