[package]
name = "aequora-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
aequora-observability = { version = "0.1.0", path = "../aequora-observability" }
aequora-protocol = { version = "0.1.0", path = "../aequora-protocol" }
aequora-store = { version = "0.1.0", path = "../aequora-store" }
aequora-transport = { version = "0.1.0", path = "../aequora-transport" }
aequora-types = { version = "0.1.0", path = "../aequora-types" }
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
