[package]
name = "aequora-clock"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
aequora-types = { version = "0.1.0", path = "../aequora-types" }

[lints]
workspace = true

